spring:
  application:
    name: aws-dynamodb-rds-sample-application
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DBNAME}
    username: rdsuser
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}

amazon:
  aws:
    accessKey: ${AMAZON_AWS_ACCESS_KEY}
    secretKey: ${AMAZON_AWS_SECRET_KEY}

application:
  migration:
    threads-count: ${APPLICATION_MIGRATION_THREADS_COUNT}