package com.rastiehaiev.aws.dynamodb.rds.sample.entity.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.rastiehaiev.aws.dynamodb.rds.sample.constants.ProjectConstants;
import com.rastiehaiev.aws.dynamodb.rds.sample.model.ProgrammingLanguage;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.List;

@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
@DynamoDBTable(tableName = ProjectConstants.CANDIDATE_TABLE_NAME)
public class DynamoDbCandidate {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String firstName;

    @DynamoDBAttribute
    private String lastName;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private ProgrammingLanguage programmingLanguage;

    private List<DynamoDbExperienceItem> experience = new ArrayList<>();

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    @DynamoDBIndexHashKey(globalSecondaryIndexName = ProjectConstants.MIGRATION_STATUS_GLOBAL_INDEX_NAME)
    private MigrationStatus migrationStatus = MigrationStatus.NONE;
}
